_BASE_: '../baseline.yml'

TAG: 'argoverse_baseline'

GPUS: [0]

BATCHSIZE: 1
TIME_RECEPTIVE_FIELD: 2
N_FUTURE_FRAMES: 4

DATASET:
  NAME: 'argoverse'
  DATAROOT: './data/argoverse'

IMAGE:
  H: 1200
  W: 1920
  RESIZE_SCALE: 0.25

MODEL:
  SUBSAMPLE: False

LOGGING_INTERVAL: 100

N_WORKERS: 2
